### ISSUE TITLE
Basic Usage

### ISSUE THREAD

**Issue by doublejosh** [adamkiss/metalsmith-virtual-pages#4]
Hope this isn't too much of a support request. I'm trying to understand the basics of this plugin. Documentation is a little slim.

It seems like you're suppose to use the JSON data file to generate source files, which then get fed into Metalsmith... rather than generate the final page from the data alone. In the example these are markdown. Then you can use layouts, partials, permalinks, etc to build pages.

With that understanding, the basics don't seem to work...

```
>> /SITE/node_modules/metalsmith-prismic-server/src/build.js:11
>>         throw err;
>>         ^
>> 
>> TypeError: Cannot read property 'length' of undefined
>>     at module.exports (/SITE/node_modules/is-utf8/is-utf8.js:5:20)
>>     at renderFile (/SITE/node_modules/metalsmith-engine-jstransformer/dist/render-file.js:26:8)
>>     at /SITE/node_modules/metalsmith-engine-jstransformer/dist/index.js:26:23
>>     at Promise (<anonymous>)
>>     at Engine.render (/SITE/node_modules/metalsmith-engine-jstransformer/dist/index.js:24:14)
>>     at /SITE/node_modules/metalsmith-in-place/dist/index.js:44:21
>>     at Array.map (<anonymous>)
>>     at Ware.<anonymous> (/SITE/node_modules/metalsmith-in-place/dist/index.js:43:8)
>>     at Ware.<anonymous> (/SITE/node_modules/wrap-fn/index.js:45:19)
>>     at next (/SITE/node_modules/ware/lib/index.js:85:20)
>>     at /SITE/node_modules/wrap-fn/index.js:121:18
>>     at /SITE/node_modules/wrap-fn/index.js:81:35
>>     at Array.<anonymous> (/SITE/node_modules/vow/lib/vow.js:754:56)
>>     at Immediate.callFns [as _onImmediate] (/SITE/node_modules/vow/lib/vow.js:24:35)
>>     at runCallback (timers.js:781:20)
>>     at tryOnImmediate (timers.js:743:5)
```

Data file...
```json
{
  "myCollections": {
    "my-collection/page-name.html": {
      "title": "EZ3D",
      "contents": "title: \"{{ title }}\"layout: \"page.html\""
    },
    "my-collection/another-page.html": {
      "title": "SLANTRANGE",
      "contents": "title: \"{{ title }}\"layout: \"page.html\""
    },
  }
}
```

**Comment by adamkiss** [comment]
@doublejosh I have used this plugin practically as it is ever since it was created, but haven't really touched the code (you can see that latest commit was ~2 years ago), and haven't actually expected anyone to use it :D I've since moved on from metalsmith, but I'll try to help you. Give me few minutes to familiarize with the code base again, cool?

**Comment by adamkiss** [comment]
Looking at the code, your data should work, assuming:
- the data is in a variable, e.g. `data`
- you're calling the plugin via `virtualFiles( data.myCollections )`, not `virtualFiles( data )`, because that's where your files are defined.

But to be honest, you might be better of just rewriting thething to javascript as your own local plugin, or republish it once you got it working — I haven't touched coffescript for over two years, and I suppose this is deprecated now. Sorry and good luck!

**Comment by doublejosh** [comment]
Thanks for looking @adamkiss!  I couldn't get past the error, but found success with [metalsmith-json-to-files](https://github.com/woodyrew/metalsmith-json-to-files) ...which you noted was rather similar.

That plugin's approach loads data from the JSON file but controls templating via front-matter and layouts. Ended up working fine for me.  Not having to transform my JSON API data was big plus too.  Hope this thread is useful to someone.
